name: test-environment
channels:
  - conda-forge
dependencies:
  - distributed
  - toolz
  - sphinx
  - dask
  - pyyaml
  - pyproj
  - coveralls
  - coverage
  - codecov
  - behave
  - mock
  - numpy
  - xarray
  - satpy
  - pyspectral
  - h5netcdf
  - pyorbital
  - pytest
  - pytest-cov
  - pip
  - pip:
    - trollsift
